### PR TITLE
Bic pen definitions updated: 2023-08-04

### PR DESCRIPTION
**Pull request by led**
Bic colours updated and missing pens added.

### CODE REVIEW

**Comment by SonarSonic** [comment]
Looks great thank you @led !

**Comment by SonarSonic** [comment]
@led I noticed the Yellow Bic Intensity and thought this was possibly a typo so changed it too another yellow, which may not be a great match.

**Comment by led** [comment]
I'll take another look. The yellow's a bugger to match as it's fluorescent.

**Comment by SonarSonic** [comment]
Here's the commit, with a fix for now

(https://github.com/SonarSonic/DrawingBotV3/commit/ef03a36b1f131169cca67f4396b307d547b9f107)

**Pull request merged**
